version: "3.7"

networks:
  backend:
    driver: bridge

services:
  ### PostgreSQL ###########################################
  postgres:
    build:
      context: ./postgres
      shm_size: 256mb
    command: postgres -c 'max_connections=1500' -c 'shared_buffers=150MB'
    shm_size: 1gb
    volumes:
      - ~/.go-hma-parser/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    restart: on-failure

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www:cached
    expose:
      - "9000"
    networks:
      - backend

  ### Nginx ##############################################
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites:/etc/nginx/sites-available
      - ../:/var/www:cached
    links:
      - php-fpm
    networks:
      - backend

